### ISSUE TITLE
Returned frames expose inner state

### ISSUE THREAD

**Issue by MarkJeronimus** [DhyanB/Open-Imaging#2]
GifImage.getFrame(int) returns an internal representation of the animation.

This has two consequences:

- Internal state is exposed to the user, akin to returning arrays or modifiable collections or exporting public fields in the API. Very bad practice in general.
- There's no easy way to obtain the animation as a sequence of separate images.

This behavior is undocumented, and lead to a bug in my application, where I saw an animation of only the last frame.

Fortunately the API doesn't have to change in order to fix this, keeping backwards compatibility.

		public BufferedImage getFrame(int index) {
			if (img == null || index < prevIndex) { // (Re)Init
				img = new BufferedImage(width, height, 2); // 2 = ARGB
				prevImg = new BufferedImage(width, height, 2);
				prevIndex = -1;
				prevDisposal = 2;
			}
			// Draw current frame on top of previous frames
			for (int i = prevIndex + 1; i <= index; i++) {
				GifFrame fr = frames.get(i);
				drawFrame(fr);
				prevIndex = i;
				prevDisposal = fr.disposalMethod;
			}

			BufferedImage copy = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
			Graphics      g    = copy.createGraphics();
			try {
				g.drawImage(img, 0, 0, null);
			} finally {
				g.dispose();
			}
			return copy;
		}

**Comment by DhyanB** [comment]
Should be fixed in v1.09. Could you please test if this works for you?
